//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atum.Studio {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Branding_Loctite {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Branding_Loctite() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Atum.Studio.Branding_Loctite", typeof(Branding_Loctite).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap About_Logo {
            get {
                object obj = ResourceManager.GetObject("About_Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://atum3d.sharepoint.com/_layouts/15/guestaccess.aspx?docid=09a3c5dcc08be43748fae1ea30d2b3d4c&amp;authkey=AWvRzFt1q1TNLodXszlbamE&amp;e=cb2230ff0c514429bd28bdcb02fffb3a.
        /// </summary>
        internal static string AdditiveManufacturingDeviceDLPStation5_XY100 {
            get {
                return ResourceManager.GetString("AdditiveManufacturingDeviceDLPStation5_XY100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://localhost/atum3d/materialcatalogs/atum3D/DLPStation5/100/_materialcatalog.xml.
        /// </summary>
        internal static string AdditiveManufacturingDeviceDLPStation5_XY100_OFFLINE {
            get {
                return ResourceManager.GetString("AdditiveManufacturingDeviceDLPStation5_XY100_OFFLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://atum3d.sharepoint.com/_layouts/15/guestaccess.aspx?docid=0c0cf133a8f0749ccaa5c52262a248771&amp;authkey=ASlHvWxtZd12rDhKUN2BCk0&amp;e=f3a51fc1a4794c10a2ae9f3846a86a5a.
        /// </summary>
        internal static string AdditiveManufacturingDeviceDLPStation5_XY50 {
            get {
                return ResourceManager.GetString("AdditiveManufacturingDeviceDLPStation5_XY50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://localhost/atum3d/materialcatalogs/atum3D/DLPStation5/75/_materialcatalog.xml.
        /// </summary>
        internal static string AdditiveManufacturingDeviceDLPStation5_XY50_OFFLINE {
            get {
                return ResourceManager.GetString("AdditiveManufacturingDeviceDLPStation5_XY50_OFFLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://atum3d.sharepoint.com/_layouts/15/guestaccess.aspx?docid=010e1e154c58b4c96947590d3de3b131d&amp;authkey=AVpcuQ83Xi8sKI7fRs1ovGc&amp;e=dac869fac407406e80eef9d9e86ac2a6.
        /// </summary>
        internal static string AdditiveManufacturingDeviceDLPStation5_XY75 {
            get {
                return ResourceManager.GetString("AdditiveManufacturingDeviceDLPStation5_XY75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://localhost/atum3d/materialcatalogs/atum3D/DLPStation5/50/_materialcatalog.xml.
        /// </summary>
        internal static string AdditiveManufacturingDeviceDLPStation5_XY75_OFFLINE {
            get {
                return ResourceManager.GetString("AdditiveManufacturingDeviceDLPStation5_XY75_OFFLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #e6e6e6.
        /// </summary>
        internal static string Button_BackColor_LightGray {
            get {
                return ResourceManager.GetString("Button_BackColor_LightGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #1E2125.
        /// </summary>
        internal static string Button_BackgroundColor_Dark {
            get {
                return ResourceManager.GetString("Button_BackgroundColor_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #282E33.
        /// </summary>
        internal static string Button_BackgroundColor_Disabled {
            get {
                return ResourceManager.GetString("Button_BackgroundColor_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #394045.
        /// </summary>
        internal static string Button_BackgroundColor_LightDark {
            get {
                return ResourceManager.GetString("Button_BackgroundColor_LightDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #FFFFFF.
        /// </summary>
        internal static string Button_ForeColor {
            get {
                return ResourceManager.GetString("Button_ForeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #1e2125.
        /// </summary>
        internal static string Button_ForeColor_Dark {
            get {
                return ResourceManager.GetString("Button_ForeColor_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #E10001.
        /// </summary>
        internal static string Button_HighlightColor {
            get {
                return ResourceManager.GetString("Button_HighlightColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap checkbox_checked_Henkel {
            get {
                object obj = ResourceManager.GetObject("checkbox_checked_Henkel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loctite Operator Station.
        /// </summary>
        internal static string CLI_Notification_Title {
            get {
                return ResourceManager.GetString("CLI_Notification_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please contact your reseller with any questions about the software or the printer. Or you can send us a message at 
        ///https://www.loctite.com/contact-us.php.
        /// </summary>
        internal static string Contact_Content {
            get {
                return ResourceManager.GetString("Contact_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #eaeaea.
        /// </summary>
        internal static string ContextMenu_BackgroundColor {
            get {
                return ResourceManager.GetString("ContextMenu_BackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #1a1c1e.
        /// </summary>
        internal static string ContextMenu_Item_ForeColor {
            get {
                return ResourceManager.GetString("ContextMenu_Item_ForeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #394045.
        /// </summary>
        internal static string ContextMenu_Item_HighlightColor {
            get {
                return ResourceManager.GetString("ContextMenu_Item_HighlightColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ffffff.
        /// </summary>
        internal static string ContextMenu_Item_HighlightForeColor {
            get {
                return ResourceManager.GetString("ContextMenu_Item_HighlightForeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #394045.
        /// </summary>
        internal static string Form_Header_BackgroundColor {
            get {
                return ResourceManager.GetString("Form_Header_BackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to activate-lic@loctite-pr10.com.
        /// </summary>
        internal static string LicenseManager_EmailAddress {
            get {
                return ResourceManager.GetString("LicenseManager_EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Loctite_SplashScreen {
            get {
                object obj = ResourceManager.GetObject("Loctite_SplashScreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon MainForm_Icon {
            get {
                object obj = ResourceManager.GetObject("MainForm_Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator Station.
        /// </summary>
        internal static string MainForm_StudioName {
            get {
                return ResourceManager.GetString("MainForm_StudioName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator Station {0}.{1}.{2}.
        /// </summary>
        internal static string MainForm_Title {
            get {
                return ResourceManager.GetString("MainForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #394045.
        /// </summary>
        internal static string Menu_BackgroundColor {
            get {
                return ResourceManager.GetString("Menu_BackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #FFFFFF.
        /// </summary>
        internal static string Menu_Item_ForeColor {
            get {
                return ResourceManager.GetString("Menu_Item_ForeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #E10001.
        /// </summary>
        internal static string Menu_Item_HighlightColor {
            get {
                return ResourceManager.GetString("Menu_Item_HighlightColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap printer_calibration_henkel {
            get {
                object obj = ResourceManager.GetObject("printer_calibration_henkel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://atum3d.sharepoint.com/_layouts/15/guestaccess.aspx?docid=09a3c5dcc08be43748fae1ea30d2b3d4c&amp;authkey=AWvRzFt1q1TNLodXszlbamE&amp;e=cb2230ff0c514429bd28bdcb02fffb3a.
        /// </summary>
        internal static string SoftwareUpdate_Url {
            get {
                return ResourceManager.GetString("SoftwareUpdate_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #E10001.
        /// </summary>
        internal static string Textbox_HighlightColor_Error {
            get {
                return ResourceManager.GetString("Textbox_HighlightColor_Error", resourceCulture);
            }
        }
    }
}
