//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atum.Studio.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color SlicerNormalColor {
            get {
                return ((global::System.Drawing.Color)(this["SlicerNormalColor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Orange")]
        public global::System.Drawing.Color FaceFacingDown {
            get {
                return ((global::System.Drawing.Color)(this["FaceFacingDown"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color SlicerBackgroundColor {
            get {
                return ((global::System.Drawing.Color)(this["SlicerBackgroundColor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("57, 64, 69")]
        public global::System.Drawing.Color SceneGroundColor {
            get {
                return ((global::System.Drawing.Color)(this["SceneGroundColor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color FaceHorizontal {
            get {
                return ((global::System.Drawing.Color)(this["FaceHorizontal"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gray")]
        public global::System.Drawing.Color DefaultSupportColor {
            get {
                return ((global::System.Drawing.Color)(this["DefaultSupportColor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightGray")]
        public global::System.Drawing.Color DefaultSurfaceSupportColor {
            get {
                return ((global::System.Drawing.Color)(this["DefaultSurfaceSupportColor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color DefaultSurfaceSupportFaceSelectedColor {
            get {
                return ((global::System.Drawing.Color)(this["DefaultSurfaceSupportFaceSelectedColor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yellow")]
        public global::System.Drawing.Color DefaultSurfaceSupportFaceColor {
            get {
                return ((global::System.Drawing.Color)(this["DefaultSurfaceSupportFaceColor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color SceneBackgroundColor {
            get {
                return ((global::System.Drawing.Color)(this["SceneBackgroundColor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://atum3d.sharepoint.com/_layouts/15/guestaccess.aspx?docid=0c3b5df5b855141b" +
            "9b5437fc55aa131ad&authkey=AVIIo5Tu16DtSOyzBCwbiFA")]
        public string MaterialCatalogURL {
            get {
                return ((string)(this["MaterialCatalogURL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("atum3D Operator Station needs to be closed to apply this update.\n\nAre you sure to" +
            " continue?")]
        public string SoftwareUpdate_Restart_Text {
            get {
                return ((string)(this["SoftwareUpdate_Restart_Text"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Aqua")]
        public global::System.Drawing.Color RotationGizmoAngleSelectionOverlay {
            get {
                return ((global::System.Drawing.Color)(this["RotationGizmoAngleSelectionOverlay"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192, 255, 255")]
        public global::System.Drawing.Color SceneControlFontColor {
            get {
                return ((global::System.Drawing.Color)(this["SceneControlFontColor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://atum3d.sharepoint.com/_layouts/15/guestaccess.aspx?docid=0c3b5df5b855141b" +
            "9b5437fc55aa131ad&authkey=AVIIo5Tu16DtSOyzBCwbiFA")]
        public string atum3D_MaterialCatalog_AtumVxx {
            get {
                return ((string)(this["atum3D_MaterialCatalog_AtumVxx"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gray")]
        public global::System.Drawing.Color SceneGroundFrontTextColor {
            get {
                return ((global::System.Drawing.Color)(this["SceneGroundFrontTextColor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("128")]
        public byte SceneViewMAGSBlendFactor {
            get {
                return ((byte)(this["SceneViewMAGSBlendFactor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Close to apply the update.")]
        public string SoftwareUpdate_Restart_Caption_Text {
            get {
                return ((string)(this["SoftwareUpdate_Restart_Caption_Text"]));
            }
        }
    }
}
